server.port: 8083
springdoc.packages-to-scan: com.online.estore.auth.api.controller
spring.profiles.active: postgres

---
spring:
  profile: postgres
  jpa:
    database: POSTGRESQL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.globally_quoted_identifiers: false
    hibernate.validationQuery: select 1
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          jdbc-url: jdbc:postgresql://localhost:5432/postgres
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres


