server.port: 8082
spring.data.rest.base-path: /api
springdoc.packages-to-scan: com.online.estore.api.controller

#spring.profiles.active: postgres

---
spring:
  profile: h2
  jpa:
    database: H2
    show-sql: true
    hibernate.ddl-auto: none
    hibernate.validationQuery: select 1
    properties.hibernate.globally_quoted_identifiers: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
    locations: classpath:db/migration/h2
h2.console.enabled: true

---
spring:
  profile: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: none
    hibernate.validationQuery: select 1
    properties.hibernate.globally_quoted_identifiers: false
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


